### ISSUE TITLE
Optimize header banner

### ISSUE THREAD

**Issue by jakemer** [jakemer/jakemer.github.io#1]
Header banner takes a while to load. Find a way to optimize it, and possibly include as base64 code in the stylesheet since this is a single page app/website.

**Comment by radium-v** [comment]
For a one-time optimization, you can use [ImageOptim](https://imageoptim.com/).

There's also [gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin) but I haven't used it.

**Comment by jakemer** [comment]
@radium-v Do you think it's a bad idea to base64 and inline the banner backround image? I've reduced it to ~400kb locally, but I'm afraid that it will block the loading of the css too much

**Comment by jakemer** [comment]
Closing for now
